# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metrica',
            fields=[
                ('nombre', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('c', 'Custom'), ('d', 'Disk'), ('p', 'CPU'), ('n', 'Network')], default='c', max_length=1)),
                ('alta', models.DateTimeField(auto_now_add=True)),
                ('modificacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.TextField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Métrica',
                'verbose_name_plural': 'Métricas',
            },
        ),
    ]
